services:
    ci-bot:
        build: .
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
        environment:
            APP_ID: ${APP_ID}
            PRIVATE_KEY: /run/secrets/github_key
            WEBHOOK_SECRET: /run/secrets/webhook_secret
            PORT: 3001
        secrets:
            - github_app_key
            - webhook_secret
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 5s
        networks: [traefik]
        labels:
            - traefik.enable=true
            - traefik.http.routers.ci-bot.rule=Host(`ci.slimevr.io`)
            - traefik.http.routers.ci-bot.tls=true
            - traefik.http.routers.ci-bot.tls.certresolver=letsencrypt
            - traefik.http.services.ci-bot.loadbalancer.server.port=3001
secrets:
    github_app_key:
        file: ./github_key.pem
    webhook_secret:
        file: ./webhook_secret.txt
networks:
    traefik:
        external: true
